<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Config.yaml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Config.yaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.0.6" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="logs\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FusionCodec\FusionCodec.csproj" />
  </ItemGroup>

</Project>
